name: Test and Deploy
on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: connect to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: scp -r continuous_deployment ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}/home/
      ##- name: install dependencies
      #  run:
      #    pip install gunicorn
      #- name: push files
      #  run: scp -r continuous_deployment ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/home/