Name: Test and Deploy
on:
  push:
    branches: [main]

jobs:
  run_tests:
    runs_on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest